Repository ParallelTask/dinoloop, pull requests merged in 2018-08, with the labels that each got.

#27 Code refactor - V2
  .github/ISSUE_TEMPLATE/bug_report.md
  .vscode/settings.json
  notes/RELEASES.md
  npm/README.md
  npm/package.json
  src/api/dino.ts
  src/modules/entities/http.response.message.ts
  src/modules/router/dino.router.ts
Labels: Refactor

#28 Add e2e tests
  src/modules/core/dino.controller.ts
  tests/index.ts
  tests/integration/api.controller.spec.ts
  tests/integration/app.middleware.spec.ts
  tests/integration/attribute.spec.ts
  tests/integration/attributes.spec.ts
  tests/integration/error.controller.spec.ts
  tests/integration/index.ts
  tests/integration/init.ts
  tests/integration/parse.spec.ts
  tests/integration/query.param.spec.ts
  tests/integration/segments.spec.ts
  tests/unit/fakes/fakes.ts
  tests/unit/fakes/index.ts
  tests/unit/karma.conf.js
  tests/unit/modules/utility/dino.utility.spec.ts
Labels: missing tests

#30 Custom httpexception and httpresponse
  src/index.ts
  src/modules/builtin/exceptions/exceptions.ts
  src/modules/builtin/http_response/http.response.ts
  src/modules/builtin/http_response/index.ts
  src/modules/entities/http.response.message.ts
  src/test_export/index.ts
  tests/integration/http.exception.spec.ts
  tests/integration/http.response.spec.ts
  tests/unit/modules/builtin/exceptions/exceptions.spec.ts
  tests/unit/modules/builtin/http_response/http.response.spec.ts
  tests/unit/modules/builtin/middlewares/http.exception.middleware.spec.ts
  tests/unit/modules/builtin/middlewares/http.response.middleware.spec.ts
Labels: enhancement

#31 add BindNumber, BindInteger, and BindBoolean
  examples/parse_api/src/app/controllers/home.controller.ts
  src/api/attributes.ts
  tests/integration/parse.spec.ts
Labels: enhancement

#32 add Regex handler and e2e tests
  .vscode/settings.json
  README.md
  examples/basic_start/src/app/controllers/home.controller.ts
  examples/dino_api/src/app/controllers/base.exception.controller.ts
  notes/RELEASES.md
  src/api/attributes.ts
  src/api/dino.ts
  src/modules/builtin/exceptions/exceptions.ts
  src/modules/builtin/parse_handlers/constants.ts
  src/modules/builtin/parse_handlers/handlers.ts
  tests/integration/api.controller.spec.ts
  tests/integration/app.middleware.spec.ts
  tests/integration/attributes.spec.ts
  tests/integration/controller.inheritance.spec.ts
  tests/integration/controller.middleware.spec.ts
  tests/integration/dinowares.flow.spec.ts
  tests/integration/error.controller.spec.ts
  tests/integration/http.response.spec.ts
  tests/integration/parse.spec.ts
  tests/integration/query.param.spec.ts
  tests/unit/api/attributes.spec.ts
  tests/unit/modules/builtin/exceptions/exceptions.spec.ts
  tests/unit/modules/builtin/middlewares/action.exception.middleware.spec.ts
  tests/unit/modules/builtin/parse_handlers/handlers.spec.ts
Labels: enhancement, missing tests, refactor

#33 Update es5 to es6
  examples/basic_start/tsconfig.json
  examples/dino_api/tsconfig.json
  examples/http_verb/tsconfig.json
  examples/inversify_basic/tsconfig.json
  examples/parse_api/tsconfig.json
  examples/task_context/tsconfig.json
  npm/README.md
  npm/package.json
  src/modules/core/dino.container.ts
  src/modules/utility/dino.utility.ts
  src/modules/utility/object.utility.ts
  tests/unit/modules/core/dino.container.two.spec.ts
  tests/unit/modules/utility/dino.utility.spec.ts
  tests/unit/modules/utility/object.utility.spec.ts
  tsconfig.json
Labels: bug, enhancement

#35 Update readme to v2.1.0
  .vscode/settings.json
  README.md
Labels: docs-edit
